import {supabase,isConfigured,setupGlobalSearch,poster} from "./supabase.js";
import {card,showModal,wireModal} from "./ui.js";
setupGlobalSearch();wireModal();
const fallback=[{title:"The Boys",genre_id:1,content_type:"Series",release_year:2019,rating:8.7,description:"Superheroes are treated as celebrities while a group of vigilantes exposes their secrets.",poster_url:"https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg"},{title:"Interstellar",genre_id:8,content_type:"Movie",release_year:2014,rating:8.7,description:"Astronauts travel through a wormhole searching for a new home.",poster_url:"https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"},{title:"Inception",genre_id:8,content_type:"Movie",release_year:2010,rating:8.8,description:"A skilled thief enters dreams to steal and plant information.",poster_url:"https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg"},{title:"The Dark Knight",genre_id:1,content_type:"Movie",release_year:2008,rating:9.0,description:"Batman faces a criminal mastermind who creates chaos across Gotham.",poster_url:"https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg"},{title:"Reacher",genre_id:1,content_type:"Series",release_year:2022,rating:8.1,description:"An ex-military investigator uncovers a dangerous conspiracy.",poster_url:"https://image.tmdb.org/t/p/w500/SNx5W7F8q7dY8Q4G7kKqZ8Y3.jpg"},{title:"RRR",genre_id:1,content_type:"Movie",release_year:2022,rating:7.9,description:"Two revolutionaries form an unexpected friendship.",poster_url:"https://placehold.co/500x750/16232d/ffffff?text=RRR"}];
async function getMovies(){if(!isConfigured())return fallback;const{data,error}=await supabase.from("movies").select("*").order("rating",{ascending:false});return error?(console.error(error),fallback):(data||[])}
function fill(id,items){const row=document.getElementById(id);if(!row)return;row.innerHTML="";items.slice(0,10).forEach(m=>row.appendChild(card(m,showModal)))}
const movies=await getMovies(),hero=movies[0];
if(hero){document.getElementById("heroTitle").textContent=hero.title;document.getElementById("heroDescription").textContent=hero.description||"";document.getElementById("heroMeta").innerHTML=`<span>${hero.release_year||""}</span><span>${hero.content_type||""}</span><span>IMDb ${hero.rating||"N/A"}</span>`;document.querySelector(".hero").style.backgroundImage=`linear-gradient(90deg,#080d12 0%,#101820c7 38%,#10182030 72%),url("${poster(hero.poster_url,hero.title)}")`}
fill("popularMovies",movies.filter(m=>m.content_type==="Movie"));fill("popularSeries",movies.filter(m=>m.content_type==="Series"));fill("actionRow",movies.filter(m=>m.genre_id===1||m.genre_id===2));fill("sciFiRow",movies.filter(m=>m.genre_id===8));fill("indianRow",movies.filter(m=>["Hindi","Telugu","Tamil","Kannada"].includes(m.language)));
document.getElementById("heroTrailer")?.addEventListener("click",()=>hero&&showModal(hero));document.getElementById("heroWatch")?.addEventListener("click",()=>hero&&showModal(hero));